---

- name: install jdk
  yum:
    name:  java-1.8.0-openjdk-devel
    state: latest
  tags:
    - install_jdk

# - name: fetch springboot student repo
#   git:

- name: inject application configuration to application.properties
  template:
    src: application.properties.j2
    dest: ./student-app/src/main/resources/application.properties
  delegate_to: localhost
  tags:
    - generate_application_properties

- name: create source code archive
  archive:
    path: ./student-app
    dest: /tmp/app.gz
  delegate_to: localhost
  tags:
    - create_source_archive

- name: install source code in tomcat
  unarchive:
    src: /tmp/app.gz
    dest: "{{ TOMCAT_APP_HOME }}"
  tags:
    - install_source

- name: build student service
  command: /opt/gradle/bin/gradle build -b "{{ APPLICATION_HOME }}"/build.gradle
  register: result
  notify: restart student.service
  tags:
    - build_student_app

- name: create systemd service wrapper for app
  template:
    src: student.service.j2
    dest: /lib/systemd/system/student.service
  notify: restart student.service
  tags:
    - create_systemd_service

- name: enable app systemd
  service:
    name: student.service
    enabled: yes
    state: started
